server:
  port: ":8080"
  log_level: "warn"

postgres:
  host: "postgres"
  port: 5432
  username: "your-user"
  password: "your-password"
  database: "database"
  autocreate: true

minio:
  endpoint: "minio:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "mybucket"

redis:
  address: "redis:6379"
  password: ""
  db: 0

telegram_config:
  bot_token: "your-bot-token"
  timeout: 120s
  bot_address: ""
